name: 'upload-workshop-item'
description: 'A GitHub Action to upload items to the Steam Workshop'

branding:
  icon: 'upload-cloud'
  color: 'blue'

runs:
  using: 'docker'
  image: 'Dockerfile'

  steps:
    - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }}| xargs)"
      - name: echo the changed files for kicks
        run: |
          for i in ${{ steps.getfile.outputs.files }}
          do
              echo $i
          done
    args:
    - ${{ inputs.path }}
    - ${{ inputs.steamAcct }}
    - ${{ inputs.steamPasswd }}
    - ${{ inputs.ssfncontents }}
    - ${{ steps.getfile.outputs.files }}

inputs:
  path:
    description: "The relative base path of your mods in the repo. Include trailing slash"
    required: true
    default: 'Mods'
  steamAcct:
    description: "Steam account name to login with"
    required: true
  steamPasswd:
    description: "Steam password (use secrets to store)"
    required: true
  files:
    description: "List of files that have changed in the repo"
    required: true
  ssfncontents:
    description: "base64 of the steam SSFN file that has authorized the account being used. Used for MFA"
    required: false