name: 'upload-workshop-item'
description: 'A GitHub Action to upload items to the Steam Workshop'

branding:
  icon: 'upload-cloud'
  color: 'blue'

runs:
  using: 'composite'
  steps:
    - id: setup-steamcmd
      uses: CyberAndrii/setup-steamcmd@v1.2.0
    - id: update_workshop
      env:
        path: ${{ inputs.path }}
        steamAcct: ${{ inputs.steamAcct }}
        SteamConfigVDF: ${{ inputs.steamConfigVdf}}
        modNames: ${{ inputs.modNames}}
        STEAM_CMD: ${{ steps.setup-steamcmd.outputs.executable }}
      run: |
        git config --global --add safe.directory /github/workspace
        chmod +x ${{ github.action_path }}/steamupload.sh
        ${{ github.action_path }}/steamupload.sh
      shell: bash
inputs:
  path:
    description: "The relative base path of your mods in the repo. Do not include trailing slash. This limits where the action references"
    required: true
    default: '!Mods'
  modNames:
    description: "Name of VDF file(s) to upload. For multiple uploads in one run, separate them by a space. Must NOT include the extension Eg: `DraconisOres6`"
    required: true
  steamAcct:
    description: "Steam account name to login with"
    required: true
  steamConfigVdf:
    description: "plaintext steam config vdf generated for the account being used. Used for MFA"
    required: true
